### ISSUE TITLE
Error: failed to pipe response and Error: OpenAI API returned an error

### ISSUE THREAD

**Issue by paulineczkapl** [yazinsai/srt-ai#11]
Nothing happend, when I try to translate srt file. 
What's wrong?

**Comment by paulineczkapl** [comment]
⨯ Error: failed to pipe response
    at pipeToNodeResponse (C:\Users\pauli\Desktop\Translator\srt-ai\node_modules\next\dist\server\pipe-readable.js:111:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendResponse (C:\Users\pauli\Desktop\Translator\srt-ai\node_modules\next\dist\server\send-response.js:40:13)
    at async doRender (C:\Users\pauli\Desktop\Translator\srt-ai\node_modules\next\dist\server\base-server.js:1360:25)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\pauli\Desktop\Translator\srt-ai\node_modules\next\dist\server\base-server.js:1552:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\pauli\Desktop\Translator\srt-ai\node_modules\next\dist\server\base-server.js:1460:28)
    at async DevServer.renderPageComponent (C:\Users\pauli\Desktop\Translator\srt-ai\node_modules\next\dist\server\base-server.js:1843:24)
    at async DevServer.renderToResponseImpl (C:\Users\pauli\Desktop\Translator\srt-ai\node_modules\next\dist\server\base-server.js:1881:32)
    at async DevServer.pipeImpl (C:\Users\pauli\Desktop\Translator\srt-ai\node_modules\next\dist\server\base-server.js:909:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\pauli\Desktop\Translator\srt-ai\node_modules\next\dist\server\next-server.js:266:17)
    at async DevServer.handleRequestImpl (C:\Users\pauli\Desktop\Translator\srt-ai\node_modules\next\dist\server\base-server.js:805:17) {
  [cause]: Error: OpenAI API returned an error
      at retrieveTranslation (webpack-internal:///(rsc)/./app/api/route.ts:46:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.start (webpack-internal:///(rsc)/./app/api/route.ts:62:38)
}

**Comment by romanrsr** [comment]
same here

**Comment by romantci2710** [comment]
⨯ Error: failed to pipe response
    at pipeToNodeResponse (C:\Users\admin\srt-ai\node_modules\next\dist\server\pipe-readable.js:111:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendResponse (C:\Users\admin\srt-ai\node_modules\next\dist\server\send-response.js:40:13)
    at async doRender (C:\Users\admin\srt-ai\node_modules\next\dist\server\base-server.js:1360:25)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\admin\srt-ai\node_modules\next\dist\server\base-server.js:1552:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\admin\srt-ai\node_modules\next\dist\server\base-server.js:1460:28)
    at async DevServer.renderPageComponent (C:\Users\admin\srt-ai\node_modules\next\dist\server\base-server.js:1843:24)
    at async DevServer.renderToResponseImpl (C:\Users\admin\srt-ai\node_modules\next\dist\server\base-server.js:1881:32)
    at async DevServer.pipeImpl (C:\Users\admin\srt-ai\node_modules\next\dist\server\base-server.js:909:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\admin\srt-ai\node_modules\next\dist\server\next-server.js:266:17)
    at async DevServer.handleRequestImpl (C:\Users\admin\srt-ai\node_modules\next\dist\server\base-server.js:805:17) {
  [cause]: Error: OpenAI API returned an error
      at retrieveTranslation (webpack-internal:///(rsc)/./app/api/route.ts:46:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.start (webpack-internal:///(rsc)/./app/api/route.ts:62:38)

**Comment by mateuspaiao** [comment]
Same problem here

**Comment by froster2006** [comment]
same error here

**Comment by macleod-be** [comment]
I had the same issues, no other debug info available in the app.
So what I did is using the postmancollection (- https://www.postman.com/devrel/workspace/openai/documentation/13183464-90abb798-cb85-43cb-ba3a-ae7941e968da )
And entered my api-key
1. test with a GET -> ok
2. test with a POST -> not ok
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}
So the error was not in de code of Yazin, but in API request !!
Finally I found the answer on: https://platform.openai.com/docs/guides/production-best-practices/managing-billing-limits
...
To begin using the OpenAI API, enter your [billing information](https://platform.openai.com/account/billing/overview). If no billing information is entered, you will still have login access but will be unable to make API requests.
...
That's what I did.
After aprox 1 hour later, my postman POST was working
I restarted srt-ai: Everything worked :-)

**Comment by froster2006** [comment]
Thank! working for me now

**Comment by bwvanlith** [comment]
Doesn't work for me.

My resulting translations have skipped lines because of this (I assume).

**Comment by GGMaia** [comment]
So is it necessary to pay to use the API after all? Or just enter your card details and you are authorized to use the API?

**Comment by mlo0352** [comment]
Thanks, macleod_be for checking the error. I had that suspicion. I suspect that this entire project may be able to be achieved using a less broad local model. I want to investigate that.

**Comment by yazinsai** [comment]
thanks for the detailed thread (and the investigation @macleod-be!)

@NeroQuill you should be able to get working API keys but there are quota limits. These are low initially, but go up with usage. See https://platform.openai.com/docs/guides/rate-limits/usage-tiers?context=tier-three
