### ISSUE TITLE
breaking error when translating

### ISSUE THREAD

**Issue by andreasc1** [yazinsai/srt-ai#27]
couldn't get an output, i always get this error:
` ⨯ Error: failed to pipe response
    at pipeToNodeResponse (/home/kali/srt-ai/node_modules/next/dist/server/pipe-readable.js:111:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendResponse (/home/kali/srt-ai/node_modules/next/dist/server/send-response.js:40:13)
    at async doRender (/home/kali/srt-ai/node_modules/next/dist/server/base-server.js:1360:25)
    at async cacheEntry.responseCache.get.routeKind (/home/kali/srt-ai/node_modules/next/dist/server/base-server.js:1552:28)
    at async DevServer.renderToResponseWithComponentsImpl (/home/kali/srt-ai/node_modules/next/dist/server/base-server.js:1460:28)
    at async DevServer.renderPageComponent (/home/kali/srt-ai/node_modules/next/dist/server/base-server.js:1843:24)
    at async DevServer.renderToResponseImpl (/home/kali/srt-ai/node_modules/next/dist/server/base-server.js:1881:32)
    at async DevServer.pipeImpl (/home/kali/srt-ai/node_modules/next/dist/server/base-server.js:909:25)
    at async NextNodeServer.handleCatchallRenderRequest (/home/kali/srt-ai/node_modules/next/dist/server/next-server.js:266:17)
    at async DevServer.handleRequestImpl (/home/kali/srt-ai/node_modules/next/dist/server/base-server.js:805:17) {
  [cause]: Error: OpenAI API returned an error
      at retrieveTranslation (webpack-internal:///(rsc)/./app/api/route.ts:48:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.start (webpack-internal:///(rsc)/./app/api/route.ts:64:38)
`

**Comment by huybui76** [comment]
i have same error

**Comment by lucascuriel** [comment]
Same here

**Comment by ibr2020** [comment]
I have the same err

**Comment by exus85** [comment]
same error

**Comment by sajb0t** [comment]
Same issue here, cant use it.

**Comment by chungmx5** [comment]
Same here

**Comment by ivar85** [comment]
Same, any idea what the problem is ?
