### ISSUE TITLE
The tool does not work - Error: failed to pipe response

### ISSUE THREAD

**Issue by joaodejesus** [yazinsai/srt-ai#33]
I carried out all the steps, and added the Openai API, and when I ask to translate I simply receive the following error message:

` ⨯ Error: failed to pipe response
    at pipeToNodeResponse (C:\Users\userName\Downloads\srt-ai\node_modules\next\dist\server\pipe-readable.js:111:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendResponse (C:\Users\userName\Downloads\srt-ai\node_modules\next\dist\server\send-response.js:40:13)
    at async doRender (C:\Users\userName\Downloads\srt-ai\node_modules\next\dist\server\base-server.js:1360:25)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\userName\Downloads\srt-ai\node_modules\next\dist\server\base-server.js:1552:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\userName\Downloads\srt-ai\node_modules\next\dist\server\base-server.js:1460:28)
    at async DevServer.renderPageComponent (C:\Users\userName\Downloads\srt-ai\node_modules\next\dist\server\base-server.js:1843:24)
    at async DevServer.renderToResponseImpl (C:\Users\userName\Downloads\srt-ai\node_modules\next\dist\server\base-server.js:1881:32)
    at async DevServer.pipeImpl (C:\Users\userName\Downloads\srt-ai\node_modules\next\dist\server\base-server.js:909:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\userName\Downloads\srt-ai\node_modules\next\dist\server\next-server.js:266:17)
    at async DevServer.handleRequestImpl (C:\Users\userName\Downloads\srt-ai\node_modules\next\dist\server\base-server.js:805:17) {
  [cause]: Error: OpenAI API returned an error
      at retrieveTranslation (webpack-internal:///(rsc)/./app/api/route.ts:48:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.start (webpack-internal:///(rsc)/./app/api/route.ts:64:38)
}`

The message informs that the cause of the error is the Openai API, but even installing the Openai library for node.js, the problem is not resolved. Do you know what I need to do?

**Comment by joaodejesus** [comment]
After thorough research, I discovered that the Openai API is not free and this is probably the reason for the error.

**Comment by Lempass** [comment]
Got same problem, even on paid version of Openai API

**Comment by robhuijben** [comment]
Same problem here.

**Comment by MartinNielsenDev** [comment]
I "fixed" the problem, you need to top up your OpenAI account first, if you have $0.00 this error happens.

**Comment by OuisAlhetar** [comment]
same problem here👋

**Comment by OuisAlhetar** [comment]
> I "fixed" the problem, you need to top up your OpenAI account first, if you have $0.00 this error happens.

how to do that??
should I upgrade the plan to Pro😢??

**Comment by MartinNielsenDev** [comment]
> > I "fixed" the problem, you need to top up your OpenAI account first, if you have $0.00 this error happens.
> 
> how to do that?? should I upgrade the plan to Pro😢??

https://platform.openai.com/settings/organization/billing/overview
