### ISSUE TITLE
Installed, running and nothing...

### ISSUE THREAD

**Issue by Ryurel523** [yazinsai/srt-ai#36]
I new to installing and running this kind of stuff but with google and following the instructions I was able to do install it and run it. I drag the file, select the lenguage hit translate and then goes back to the drag the file "window", no dowloaded file no error message, nothing... I think I just quickly see that its working in the translation before going back to the drag file "window" and the the read me doesnt seem to say anything on what to expect, maybe the I did something wrong when installing(?).
Running on W11 and FireFox
P.D the select file button doesnt work but I saw in these posts that is a common issue using firefox and I dont care to much for it.
P.D2 can this run a batch of str files? that would be pretty useful.

Thanks for the effort!

**Comment by accumb1s** [comment]
same here even without adblocker, where is the location of the output file ?

**Comment by Number-313** [comment]
same here, the console shows this : 
```
⨯ Error: failed to pipe response
    at pipeToNodeResponse (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\pipe-readable.js:126:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendResponse (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\send-response.js:40:13)
    at async doRender (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\base-server.js:1389:25)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\base-server.js:1581:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\base-server.js:1489:28)
    at async DevServer.renderPageComponent (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\base-server.js:1920:24)
    at async DevServer.renderToResponseImpl (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\base-server.js:1958:32)
    at async DevServer.pipeImpl (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\base-server.js:917:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\base-server.js:813:17)
    at async C:\Users\Vianney\srt-ai\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\Vianney\srt-ai\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\lib\router-server.js:173:21)
    at async handleRequest (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\lib\router-server.js:350:24)
    at async requestHandlerImpl (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\lib\router-server.js:374:13)
    at async Server.requestListener (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\lib\start-server.js:141:13) {
  [cause]: Error: OpenAI API returned an error
      at retrieveTranslation (webpack-internal:///(rsc)/./app/api/route.ts:48:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.start (webpack-internal:///(rsc)/./app/api/route.ts:64:38)
}
```
