### ISSUE TITLE
Dont Work Pls Update

### ISSUE THREAD

**Issue by maroonberett** [yazinsai/srt-ai#41]
I think there is a problem with the Openai API, the project is not working. Could you please update it? Thanks.

**Comment by caiot5** [comment]
Yeah, is failing like above:

 ⨯ Error: failed to pipe response
    at pipeToNodeResponse (/home/caio/srt-ai/node_modules/next/dist/server/pipe-readable.js:126:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendResponse (/home/caio/srt-ai/node_modules/next/dist/server/send-response.js:40:13)
    at async doRender (/home/caio/srt-ai/node_modules/next/dist/server/base-server.js:1407:25)
    at async cacheEntry.responseCache.get.routeKind (/home/caio/srt-ai/node_modules/next/dist/server/base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (/home/caio/srt-ai/node_modules/next/dist/server/base-server.js:1507:28)
    at async DevServer.renderPageComponent (/home/caio/srt-ai/node_modules/next/dist/server/base-server.js:1931:24)
    at async DevServer.renderToResponseImpl (/home/caio/srt-ai/node_modules/next/dist/server/base-server.js:1969:32)
    at async DevServer.pipeImpl (/home/caio/srt-ai/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/home/caio/srt-ai/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/home/caio/srt-ai/node_modules/next/dist/server/base-server.js:816:17)
    at async /home/caio/srt-ai/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/home/caio/srt-ai/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/home/caio/srt-ai/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/home/caio/srt-ai/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/home/caio/srt-ai/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/home/caio/srt-ai/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/home/caio/srt-ai/node_modules/next/dist/server/lib/start-server.js:141:13) {
  [cause]: Error: OpenAI API returned an error
      at retrieveTranslation (webpack-internal:///(rsc)/./app/api/route.ts:48:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.start (webpack-internal:///(rsc)/./app/api/route.ts:64:38)
}
 POST /api 500 in 1985ms

**Comment by ductu3590** [comment]
> Yeah, is failing like above:
> 
> ⨯ Error: failed to pipe response at pipeToNodeResponse (/home/caio/srt-ai/node_modules/next/dist/server/pipe-readable.js:126:15) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async sendResponse (/home/caio/srt-ai/node_modules/next/dist/server/send-response.js:40:13) at async doRender (/home/caio/srt-ai/node_modules/next/dist/server/base-server.js:1407:25) at async cacheEntry.responseCache.get.routeKind (/home/caio/srt-ai/node_modules/next/dist/server/base-server.js:1599:28) at async DevServer.renderToResponseWithComponentsImpl (/home/caio/srt-ai/node_modules/next/dist/server/base-server.js:1507:28) at async DevServer.renderPageComponent (/home/caio/srt-ai/node_modules/next/dist/server/base-server.js:1931:24) at async DevServer.renderToResponseImpl (/home/caio/srt-ai/node_modules/next/dist/server/base-server.js:1969:32) at async DevServer.pipeImpl (/home/caio/srt-ai/node_modules/next/dist/server/base-server.js:920:25) at async NextNodeServer.handleCatchallRenderRequest (/home/caio/srt-ai/node_modules/next/dist/server/next-server.js:272:17) at async DevServer.handleRequestImpl (/home/caio/srt-ai/node_modules/next/dist/server/base-server.js:816:17) at async /home/caio/srt-ai/node_modules/next/dist/server/dev/next-dev-server.js:339:20 at async Span.traceAsyncFn (/home/caio/srt-ai/node_modules/next/dist/trace/trace.js:154:20) at async DevServer.handleRequest (/home/caio/srt-ai/node_modules/next/dist/server/dev/next-dev-server.js:336:24) at async invokeRender (/home/caio/srt-ai/node_modules/next/dist/server/lib/router-server.js:174:21) at async handleRequest (/home/caio/srt-ai/node_modules/next/dist/server/lib/router-server.js:353:24) at async requestHandlerImpl (/home/caio/srt-ai/node_modules/next/dist/server/lib/router-server.js:377:13) at async Server.requestListener (/home/caio/srt-ai/node_modules/next/dist/server/lib/start-server.js:141:13) { [cause]: Error: OpenAI API returned an error at retrieveTranslation (webpack-internal:///(rsc)/./app/api/route.ts:48:15) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Object.start (webpack-internal:///(rsc)/./app/api/route.ts:64:38) } POST /api 500 in 1985ms

I also got the same error. Have you found a way to fix it yet?

**Comment by idodoron11** [comment]
I also got the same error

**Comment by Number-313** [comment]
same here : 

```
 POST /api 500 in 503ms
 GET / 200 in 99ms
 ⨯ Error: failed to pipe response
    at pipeToNodeResponse (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\pipe-readable.js:126:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendResponse (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\send-response.js:40:13)
    at async doRender (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\base-server.js:1389:25)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\base-server.js:1581:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\base-server.js:1489:28)
    at async DevServer.renderPageComponent (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\base-server.js:1920:24)
    at async DevServer.renderToResponseImpl (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\base-server.js:1958:32)
    at async DevServer.pipeImpl (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\base-server.js:917:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\base-server.js:813:17)
    at async C:\Users\Vianney\srt-ai\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\Vianney\srt-ai\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\lib\router-server.js:173:21)
    at async handleRequest (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\lib\router-server.js:350:24)
    at async requestHandlerImpl (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\lib\router-server.js:374:13)
    at async Server.requestListener (C:\Users\Vianney\srt-ai\node_modules\next\dist\server\lib\start-server.js:141:13) {
  [cause]: Error: OpenAI API returned an error
      at retrieveTranslation (webpack-internal:///(rsc)/./app/api/route.ts:48:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.start (webpack-internal:///(rsc)/./app/api/route.ts:64:38)
```

**Comment by GioPalusa** [comment]
There is a fix that makes it work here: https://github.com/yazinsai/srt-ai/pull/43
